# Start your image with a node base image
FROM golang:1.21


# Creates an app directory to hold your app’s source code
WORKDIR /app

# Copies everything from your root directory into /app
COPY go.mod .
COPY go.sum .
COPY main.go .
 
# Installs Go dependencies
RUN go mod download
 
# Builds your app with optional configuration
RUN go build -o bin .
 
# Tells Docker which network port your container listens on
EXPOSE 8081
 
# Specifies the executable command that runs when the container starts
CMD [ "/app/bin" ]